---
- name: redhat | Copying Elasticsearch GPG Key
  ansible.builtin.copy:
    src: GPG-KEY-elasticsearch
    dest: /tmp/GPG-KEY-elasticsearch
    mode: u=rw,g=r,o=r

- name: redhat | Adding Elasticsearch GPG Key
  ansible.builtin.rpm_key:
    key: /tmp/GPG-KEY-elasticsearch
    state: present
  become: true

- name: redhat | Adding auditbeat Repo
  ansible.builtin.yum_repository:
    baseurl: "{{ es_auditbeat_repo_url + '/' + es_auditbeat_major_ver + '/yum' }}"
    description: "auditbeat repository for {{ es_auditbeat_major_ver }} packages"
    enabled: true
    gpgcheck: true
    gpgkey: "{{ es_auditbeat_repo_key }}"
    name: "{{ 'auditbeat-' + es_auditbeat_major_ver }}"
    state: present
  become: true

- name: redhat | Installing auditbeat
  ansible.builtin.package:
    name: "{{ 'auditbeat-' + es_auditbeat_minor_version | string }}"
    state: present
  become: true
  register: result
  until: result is successful
