---
- name: Converge
  hosts: all
  vars:
    # Defines whether or not auditbeat is configured
    es_auditbeat_config: true
  tasks:
    - name: Include ansible-es-auditbeat
      ansible.builtin.include_role:
        name: ansible-es-auditbeat
